### ISSUE TITLE
Login design

### ISSUE THREAD

**Issue by seyiogunjuyigbe** [team-gandhi/login-page#1]
The form fields need to have labels... please add them
Also, name the placeholders as "username" and "password"
The "forgot password" should be where the"sign up" button is currently
The sign up can come underneath as "new user? sign up"

Great work!

**Comment by larrich** [comment]
If the the label fields are named "username" and "password" the placeholders should be different

**Comment by seyiogunjuyigbe** [comment]
Sure, that's cool. they should be different

**Comment by larrich** [comment]
login and sign up buttons are always together. It wont make sense if sign up is below

**Comment by seyiogunjuyigbe** [comment]
The primary CTA (call to action) is logging in, so it's logical to have it alone on that line. See attached pictures for reference


![image](https://user-images.githubusercontent.com/32278082/64948873-e9621700-d86f-11e9-89bc-37a2419a89b3.png)

![image](https://user-images.githubusercontent.com/32278082/64948964-131b3e00-d870-11e9-8577-f93c786254c2.png)

![image](https://user-images.githubusercontent.com/32278082/64949082-4eb60800-d870-11e9-9c49-3f9eef57ad32.png)

**Comment by larrich** [comment]
Noted

**Comment by larrich** [comment]
Should I make the login button short or long? and centralized

**Comment by Alphajeez96** [comment]
up there can we add an image more like a favicon

**Comment by Alphajeez96** [comment]
or something in a png format.. can the designers get us something with our group name or something

**Comment by Alphajeez96** [comment]
@larrich you using bootstrap?

**Comment by larrich** [comment]
Where please?

**Comment by larrich** [comment]
@Alphajeez96  no, figma

**Comment by seyiogunjuyigbe** [comment]
> Should I make the login button short or long? and centralized

whichever fits your design

**Comment by Alphajeez96** [comment]
> Where please?

Check the samples Seyi dropped they have a logo-like something up there

**Comment by larrich** [comment]
@Alphajeez96 done. check and see if its ok

**Comment by Alphajeez96** [comment]
> @Alphajeez96 done. check and see if its ok

seen Dear...looks good .. We going somewhere i think others have to look at it although i feel we could make it sharper or 'tusher'

**Comment by nkechi10** [comment]
![Task 1 sample](https://user-images.githubusercontent.com/53117706/64958873-e541f380-d887-11e9-9d8c-bf3dec52dacc.png)

**Comment by nkechi10** [comment]
I have seen @ larrich. Its ok too.

**Comment by GoodwillNnaji** [comment]
The above design is great... I was thinking maybe a curved call to action button would be great

**Comment by nkechi10** [comment]
[
![hng logo](https://user-images.githubusercontent.com/53117706/64976708-e3892780-d8a9-11e9-801b-1f7794dac549.png)
]
