### ISSUE TITLE
Login Page front end code

### ISSUE THREAD

**Issue by seyiogunjuyigbe** [team-gandhi/login-page#7]

**Comment by larrich** [comment]
wow..cool
but the welcome back should be at the centre
the password label should also come down a little
Please just try to follow the design prototype alignment. You guys really tried tho

**Comment by Alphajeez96** [comment]
Font type.. Border of input field...  Position of the welcome back and logo

**Comment by seyiogunjuyigbe** [comment]
> wow..cool
> but the welcome back should be at the centre
> the password label should also come down a little
> Please just try to follow the design prototype alignment. You guys really tried tho

done... thanks

**Comment by larrich** [comment]
The illustration by the right should also be centered

**Comment by larrich** [comment]
One more thing, the username and password placeholders should be centered

**Comment by Alphajeez96** [comment]
we could make use of linear icons too for UI purposes...


![screen-09 57 53 17 09 2019](https://user-images.githubusercontent.com/48554942/65027189-d0219f00-d931-11e9-9877-1ac421d3d86e.png)
 
A design i'm working on

**Comment by larrich** [comment]
@seyiogunjuyigbe  Change the Welcome back to Welcome Back. Please follow the design strictly
<img width="1563" alt="Log in page" src="https://user-images.githubusercontent.com/54288112/65028430-f2b4b780-d933-11e9-8a05-f388d5a56b06.png">

**Comment by seyiogunjuyigbe** [comment]
> One more thing, the username and password placeholders should be centered

done

**Comment by seyiogunjuyigbe** [comment]
> @seyiogunjuyigbe Change the Welcome back to Welcome Back. Please follow the design strictly
> <img alt="Log in page" width="1563" src="https://user-images.githubusercontent.com/54288112/65028430-f2b4b780-d933-11e9-8a05-f388d5a56b06.png">

done

**Comment by seyiogunjuyigbe** [comment]
> Font type.. Border of input field... Position of the welcome back and logo

position of welcome back and logo... done
font type and border of input field are as stated in the design (although I just thought of another font now...) you can refresh the page to see the changes

**Comment by seyiogunjuyigbe** [comment]
@larrich and @Alphajeez96 you can refresh the page url (https://team-gandhi-patch1.netlify.com/) to see issues corrected. Thanks again

**Comment by Alphajeez96** [comment]
@seyiogunjuyigbe job well done boss

**Comment by Alphajeez96** [comment]
@larrich the point of forgot password? no action what happens if it is forgotten? suggesting a touch in our design

**Comment by Hodre** [comment]
Seyi, the webapp isn't responsive.
I'll pull your code and see if I can do something, great work though.
