### ISSUE TITLE
Create Account page

### ISSUE THREAD

**Issue by Alphajeez96** [team-gandhi/login-page#9]

**Comment by seyiogunjuyigbe** [comment]
Great job... we'd need to unify our fonts and icons, as well as page styles.

Also align the logo and welcome text, and capitalize correctly

**Comment by Alphajeez96** [comment]
Used all uppercase.. Should be different? 
Will work on the logo

**Comment by seyiogunjuyigbe** [comment]
Should be just capitalize... 

Also check your media query breakpoints for responsiveness

**Comment by seyiogunjuyigbe** [comment]
lol.... what's that effect when you click on the input fields???

**Comment by Alphajeez96** [comment]
> Should be just capitalize...
> 
> Also check your media query breakpoints for responsiveness

it is capitalized except you referring to the label
